version: '3.1'

services:
  db:
    image: postgres:14.5-alpine
    ports:
      - '5555:5432'
    environment:
      POSTGRES_PASSWORD: 'foobar'
      POSTGRES_USER: 'foobar'
      POSTGRES_DB: 'foobar'
    command: ['postgres', '-c', 'log_statement=all']

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db
